pipeline {
    agent any
     tools {
        maven 'M3'
      }

    stages {
     stage ('Initialize') {
                      steps {
                          bat '''
                              echo "PATH = ${PATH}"
                              echo "M2_HOME = ${M2_HOME}"
                          '''
                      }
                  }
        stage('Build stage') {
            steps {
              bat 'mvn -f Backend/pom.xml clean compile'
        }
    }
    }
    post {
    always{
    cleanWs()
    }
    }


    }
